contour:
  min_area: 1000
  blur_ksize: [5,5]
  threshold_params: { … }
  scale_mm_per_px: 0.5
nms:
  iou_threshold: 0.3
nn:
  model_path: "models/yolo.pt"
  conf_thresh: 0.5
roi_masks:
  workpieces:
    - [100,50,200,150]
  tools:
    - [50,200,150,300]
